version: '3.8'

services:
    sculpin:
        container_name: sculpin
        build:
           context: .
        ports:
            - 80:8000
        volumes:
            - .:/data
        environment:
            TZ: Asia/Tokyo
        command: >
            bash -c "composer install && composer sculpin-watch"
        #command: ["tail", "-f", "/dev/null"]  # keep container running for debug

